package main

import (
	"os"

	"github.com/abik1221/Tewanay-Engineering_Intership/database"
	"github.com/abik1221/Tewanay-Engineering_Intership/middlewares"
	"github.com/abik1221/Tewanay-Engineering_Intership/routes"
	"github.com/gin-gonic/gin"

	// Swagger imports
	_ "github.com/abik1221/Tewanay-Engineering_Intership/docs" // swagger docs generated by swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"go.mongodb.org/mongo-driver/mongo"
)

var foods *mongo.Collection = database.OpenCollection(database.Client, "food")

func main() {
	router := gin.New()
	router.Use(gin.Logger(), gin.Recovery())

	// Swagger route, accessible publicly
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Your existing routes
	routes.UserRoutes(router)

	// Auth middleware applied after user routes
	router.Use(middlewares.AuthMiddleware())

	routes.FoodRoutes(router)
	routes.MenuRoutes(router)
	routes.InvoiceRoutes(router)
	routes.OrderRoutes(router)
	routes.TableRoutes(router)
	routes.OrderItemRoutes(router)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	router.Run(":" + port)
}
